name: main-workflow
on: [push]
jobs:
  client-server-unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        working-directory: ./ClientServer
        run: npm install --dev
      - name: Run Tests
        working-directory: ./ClientServer
        run: npm test
